---
strictness: veryhigh
max-line-length: 110
doc-warnings: True

pylint:
  disable:
    - too-many-arguments
    - missing-module-docstring

pycodestyle:
  disable:
    - E203 # Whitespace before ':'
    - E722 # Do not use bare 'except'

pydocstyle:
  disable:
    - D104 # Missing docstring in public package
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section ('Arguments')
    - D412 # No blank lines allowed between a section header and its content ('Arguments')
    - D413 # Missing blank line after last section ('Arguments')

bandit:
  run: true

mypy:
  run: true

mccabe:
  run: false
