# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.5.2/c2cciutils/schema.json

checks:
  versions: False
  codespell:
    ignore_re:
      - ^poetry\.lock$
  black:
    ignore_patterns_re:
      - README\.md
